In [1]:
import numpy as np


X = np.array((
    [0, 0, 1],
    [1, 1, 1],
    [0, 1, 1],
    [1, 0, 1]), dtype=float)
y = np.array((
    [0],
    [0],
    [1],
    [1]), dtype=float)


def sigmoid(t):
  return 1/(1+np.exp(-t))


def sigmoid_derivative(p):
  return p * (1 - p)


class NeuralNetwork:
  def __init__(self):
    self.weights1 = np.random.rand(3, 4)
    self.weights2 = np.random.rand(4, 1)

  def feedforward(self, x):
    self.layer1 = sigmoid(np.dot(x, self.weights1))
    self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
    return self.layer2

  def backprop(self, x, y, prediction):
    d_weights2 = np.dot(
        self.layer1.T, 2*(y - prediction) * sigmoid_derivative(prediction))
    d_weights1 = np.dot(x.T, np.dot(2 * (y - prediction) * sigmoid_derivative(
        prediction), self.weights2.T) * sigmoid_derivative(self.layer1))

    self.weights1 += d_weights1
    self.weights2 += d_weights2

  def train(self, X, y, batch_size):
    if batch_size > len(X):
      batch_size = len(X)
    batches = [[X[i: i + batch_size], y[i: i + batch_size]]
               for i in range(0, len(X), batch_size)]

    for batch in batches:
      prediction = self.feedforward(batch[0])
      self.backprop(batch[0], batch[1], prediction)

  def predict(self, X):
    return list(map(lambda x: 1 if x > 0.4 else 0, self.feedforward(X)))


NN = NeuralNetwork()
for i in range(50000):
  if i % 10000 == 0:
    print("for iteration # " + str(i) + "\n")
    print("Input : \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" + str(NN.feedforward(X)))
    print("Loss: \n" + str(np.mean(np.square(y - NN.feedforward(X)))))
    print("\n")

  NN.train(X, y, batch_size=3)


for iteration # 0

Input : 
[[0. 0. 1.]
 [1. 1. 1.]
 [0. 1. 1.]
 [1. 0. 1.]]
Actual Output: 
[[0.]
 [0.]
 [1.]
 [1.]]
Predicted Output: 
[[0.79775632]
 [0.8748627 ]
 [0.84219155]
 [0.85030337]]
Loss: 
0.36227811856111103


for iteration # 10000

Input : 
[[0. 0. 1.]
 [1. 1. 1.]
 [0. 1. 1.]
 [1. 0. 1.]]
Actual Output: 
[[0.]
 [0.]
 [1.]
 [1.]]
Predicted Output: 
[[0.00768041]
 [0.00676464]
 [0.99125698]
 [0.99563992]]
Loss: 
5.0049880532950354e-05


for iteration # 20000

Input : 
[[0. 0. 1.]
 [1. 1. 1.]
 [0. 1. 1.]
 [1. 0. 1.]]
Actual Output: 
[[0.]
 [0.]
 [1.]
 [1.]]
Predicted Output: 
[[0.00545461]
 [0.00457783]
 [0.99392458]
 [0.99711307]]
Loss: 
2.398859404303916e-05


for iteration # 30000

Input : 
[[0. 0. 1.]
 [1. 1. 1.]
 [0. 1. 1.]
 [1. 0. 1.]]
Actual Output: 
[[0.]
 [0.]
 [1.]
 [1.]]
Predicted Output: 
[[0.00447169]
 [0.00366024]
 [0.99507239]
 [0.9977221 ]]
Loss: 
1.5715884565944077e-05


for iteration # 40000

Input : 
[[0. 0. 1.]
 [1. 1. 1.]
 [0. 1. 1.]
 [1. 0. 1.]]
Actual 

In [49]:
import pandas as pd

x_for_display = [[0, 0, 1], [1, 1, 1], [0, 1, 1], [1, 0, 1]]
x_for_display = list(map(lambda x: str(x), x_for_display))

y_for_display = [0, 0, 1, 1]
pred_for_display = list(map(lambda x: x[0], NN.feedforward(X)))

data = {
    "Inputs": x_for_display,
    "Output": y_for_display,
    "Network Prediction": pred_for_display,
    "Network Output": NN.predict(X)
}

pd.DataFrame(data)

Inputs  Output  Network Prediction  Network Output
0  [0, 0, 1]       0            0.003484               0
1  [1, 1, 1]       0            0.002771               0
2  [0, 1, 1]       1            0.996206               1
3  [1, 0, 1]       1            0.998305               1